### ISSUE TITLE
Window in top-left does not appear

### ISSUE THREAD

**Issue by dpcoolbreeze** [slyh/Cities2-TrafficLightsEnhancement#105]
Hello :)
I probably doing something wrong, but the window in the top-left corner does not appear when i click on traffic light in the ingame menu, as it said in the guide.
Could you help me ?
Thanks a lot

**Comment by AProgrammablePhoenix** [comment]
I have the same issue, restarting the game did not fix this.

**Comment by krzychu124** [comment]
It you used **Gooee** mod before, make sure there's no **Gooee** folder inside these two folders (if exist) `/Mods` and `/ModsData` (`C:\Users\<your_username>\LocalLow\Colossal Order\Cities Skylines II`)

**Comment by dpcoolbreeze** [comment]
It's works ! Thank you so much !!

**Comment by dpcoolbreeze** [comment]
It's works ! Thank you so much !!

**Comment by AProgrammablePhoenix** [comment]
> It you used **Gooee** mod before, make sure there's no **Gooee** folder inside these two folders (if exist) `/Mods` and `/ModsData` (`C:\Users\<your_username>\LocalLow\Colossal Order\Cities Skylines II`)

I don't have any of these and never used Gooe (I have a fresh installation with factory settings of CS2).

**Comment by krzychu124** [comment]
> > It you used **Gooee** mod before, make sure there's no **Gooee** folder inside these two folders (if exist) `/Mods` and `/ModsData` (`C:\Users\<your_username>\LocalLow\Colossal Order\Cities Skylines II`)
> 
> I don't have any of these and never used Gooee (I have a fresh installation with factory settings of CS2).

Which means you experience different problem, I suggest posting Player.log and Player-prev.log (it's in the mentioned location). 

Just to be sure, you restarted the game after subscribing and enabling the mod, right?

**Comment by AProgrammablePhoenix** [comment]
> > > It you used **Gooee** mod before, make sure there's no **Gooee** folder inside these two folders (if exist) `/Mods` and `/ModsData` (`C:\Users\<your_username>\LocalLow\Colossal Order\Cities Skylines II`)
> > 
> > I don't have any of these and never used Gooee (I have a fresh installation with factory settings of CS2).
> 
> Which means you experience different problem, I suggest posting Player.log and Player-prev.log (it's in the mentioned location). 
> 
> Just to be sure, you restarted the game after subscribing and enabling the mod, right?

Nevermind, just restarted my computer and it works now... (which is unexpected to be fair). Thank you for your assistance.
