### ISSUE TITLE
I can't even test the v0.3 canary. Extreme slowdown/unselectable junctions

### ISSUE THREAD

**Issue by Rafario448** [slyh/Cities2-TrafficLightsEnhancement#118]
Clear savegame, clear install of the game, since i'm returning to the game, I only have this mods.
![image](https://github.com/user-attachments/assets/98f8fde1-3593-41b3-9ebb-ed753a1b4c7b)

0.3v canary isn't working at all. When I select the tool on the top left of the screen the game runs at 4fps, and I can't select any junction.

**Comment by Rafario448** [comment]
![image](https://github.com/user-attachments/assets/0780a5f5-7f4a-4249-8722-9ef1154b2d5f)

**Comment by slyh** [comment]
This issue was fixed in the update pushed yesterday. Feel free to reopen it if the problem persists, or open a new issue if you encounter other problems in the preview branch.
