### ISSUE TITLE
Pedestrians cross into protected left traffic

### ISSUE THREAD

**Issue by adalinesimonian** [slyh/Cities2-TrafficLightsEnhancement#54]
**Describe the bug**
Pedestrians walk into oncoming traffic in intersections with protected left turns.

**To Reproduce**
1. Build an intersection.
2. Configure the intersection to use protected left turns.

**Expected behaviour**
The pedestrian signal is off until the protected left turn traffic phase is over.

**Actual behaviour**
The pedestrian signal is on even when only turning traffic is being allowed through the intersection.

**Screenshots**
![Screenshot of pedestrians](https://github.com/slyh/Cities2-Various-Mods/assets/9868643/0610e020-ed6f-4062-982e-0327a7ffe71d)

![Screenshot of intersection settings](https://github.com/slyh/Cities2-Various-Mods/assets/9868643/3273c129-69e1-4d79-9675-7d561f95a542)

**Log file**
[LogOutput.log](https://github.com/slyh/Cities2-Various-Mods/files/13593914/LogOutput.log)

**Comment by slyh** [comment]
Currently the pedestrian lights are not modified to accommodate modes like protected turns. I will try to change this to better align with player's expectations.

**Comment by slyh** [comment]
The pedestrian lights should now be more aligned with expectations in [v0.2.11-alpha](https://github.com/slyh/Cities2-TrafficLightsEnhancement/releases/tag/v0.2.11).

They will now behave as shown in this diagram:

https://github.com/slyh/Cities2-TrafficLightsEnhancement/discussions/3#discussioncomment-7663483
