### ISSUE TITLE
Error Message ingame: System Update error durring GameSimulation 

### ISSUE THREAD

**Issue by KruemelGames** [slyh/Cities2-TrafficLightsEnhancement#55]
**Describe the bug**
This error pops up with Traffic Lights Enhancement Alpha AND Economy Fixer enabled (+BepIn).
I can replicate it but sadly its caused by two mods together.
The error message always apears when a building is destroyed and collapses due to rezoning. The rezoning is caused by placing a new road next to a road with buildings on it.
Error messages in log down below (pastebin links)

**To Reproduce**
Steps to reproduce the behaviour.

1. Have TLEA, Economy Fixer and BepIn enabled 
2. Place a new road on a curved road which most definatly causes a rezone on the old road.
3. Building gets destroyed because of new zoning. Building collapses.
4. Error message pops up 

Video showing it:
https://www.youtube.com/watch?v=AE_caWj97iI

**Expected behaviour**
No error message to pop up in the game. 

**Screenshots**

**Log file**
Console log:
https://pastebin.com/Dd00kgvs

Game log:
https://pastebin.com/34Vx3Dsd

BepInEx log:
https://pastebin.com/p4FBxraz

**Additional context**
I also reported this to TDW and he said he is taking a look into this.
Here is the save to reproduce this in case you need it. https://drive.google.com/drive/folders/14ngC8W83ciAJLWVxI2XHEDx7Z3_vdzgP?usp=sharing
The map is Cali Coast from Ausiguy on thunderstore.
Edit: i found a workaround for this, by disabling the collapse setting

**Comment by slyh** [comment]
I am able to replicate the same issue with only EconomyFixer installed. Since that mod only has decompiled source available, I will wait for information from TDW.

https://github.com/slyh/Cities2-Various-Mods/assets/80482978/e872f6ab-7204-46bc-837b-4519212e490b

**Comment by slyh** [comment]
Closing the issue as it is no longer relevant.
