### ISSUE TITLE
Vehicle crossing lanes to change lanes

### ISSUE THREAD

**Issue by HarryBotter2333** [slyh/Cities2-TrafficLightsEnhancement#75]
![屏幕截图 2024-01-23 213341](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/43106121/5e7809fd-be55-4c60-8f0b-02676960ab6f)
![屏幕截图 2024-01-23 212548](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/43106121/d11e3c98-caeb-43d1-98d9-5aacc99ac66c)
![屏幕截图 2024-01-23 212517](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/43106121/8915758b-de35-489f-8943-c2df982a4d6a)

1.Used no collision.
2.Checked that there is only one intersection node.
3.A tramway was built next to it, which may have break affected it ?

A newly constructed intersection discovered strange behavior of vehicles after running for a period of time.

Super fast>>>, crossing the curve directly to the straight road.

Game Save&Video check Here:https://web.tresorit.com/l/8We5H#VVduoJ4aZFUWBJiyap8ZaA

**Comment by slyh** [comment]
Thank you for reporting this bug. It is due to an oversight in connecting lanes at three-way junctions. It should be fixed in [v0.2.16-alpha](https://github.com/slyh/Cities2-TrafficLightsEnhancement/releases/tag/v0.2.16).

Please turn traffic lights off and on at the affected junctions after upgrading for the fix to apply.

**Comment by HarryBotter2333** [comment]
Thank you for your work. I tested it and it's ok so far.
I will keep the original road and test the next few versions before closing this post :)

**Comment by HarryBotter2333** [comment]
0.2.16:
Oh!!! after I revised the road today, vehicles started to force their way from the turning lane to the through lane again.
![屏幕截图 2024-01-25 171830](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/43106121/daa53124-cf11-4832-9dfc-589527a568cd)

And they seem to be stuck at a hidden node?
![屏幕截图 2024-01-25 171917](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/43106121/7c972eb0-5c68-4fdf-b8c4-a59406523d13)
![屏幕截图 2024-01-25 171724](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/43106121/2a56b196-f4f7-4b1f-8d8f-974af19680f7)

Just in case, I'd better send you the new saves.

New Saves Here:https://web.tresorit.com/l/sX0wg#MdRXrdjHLwJIJpeBOZMWLg

**Comment by slyh** [comment]
I've looked into it and found more connection issues. An overhaul would be required to fix them, which will take time.

For now, I recommend resetting the Lane Direction Tool and using the built-in road sign tools for the affected junctions.

**Comment by slyh** [comment]
I have added additional checks in [v0.2.17-alpha](https://github.com/slyh/Cities2-TrafficLightsEnhancement/releases/tag/v0.2.17) and I hope this issue is fully solved.

**Comment by HarryBotter2333** [comment]
Okay, I don't see any problems ,let's solve the next new questions.
