### ISSUE TITLE
drivers prefer turning left instead of going forward (lhd)

### ISSUE THREAD

**Issue by xxjoe2** [slyh/Cities2-TrafficLightsEnhancement#78]
hi

i found a bug with this mod. in short, drivers will turn left at interactions instead of going forward, causing a lot of traffic jams
and when the mod is disabled, everything is fine

the pic below shows, with the mod enabled, they follow the link in red, which should be the one in green

![Screenshot_20240129_004117_Brave](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/83495134/aa5fa7fb-ce25-4e87-b87c-6e1f5d933232)

hope that this issuse can be solved since this mod is very useful

thanks

**Comment by slyh** [comment]
Thank you for filing an issue report.

I need your BepInEx log file (BepInEx/LogOutput.log) and save file to better understand the issue.

**Comment by xxjoe2** [comment]
my apology

i started a new map as to give you a simplified version. turn out that it's the mod manager's problem. for unknown reason it didnt disable another mod which caused the problem


sorry and thanks for your time

**Comment by slyh** [comment]
Glad to know that you have solved the issue!

Could you share your findings so that others who encounter the same issue can benefit from them?

**Comment by xxjoe2** [comment]
sure. the problem was in fact due the CustomVehiclePathfind mod

i opted to have less traffic so in the screenshot below you wont see too many vehciles. however, you can still find a bus there marked in red, which shouldnt be there since there's no bus stop

this causes huge traffic jams since every driver will turn left and go to the inner road even it's a dead end one, and then back to the main road as indicated by the red arrows, rather than taking the normal route in green

![screenshot1](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/83495134/d09231bb-51d9-40da-bec3-bcb29da76558)


once again, i am sorry for my mistake

**Comment by slyh** [comment]
The default value of `LaneChangingPunishment` in CustomVehiclePathfind is indeed a bit too high, I can observe similar behaviour in my city.

**Comment by xxjoe2** [comment]
oh yes, thanks for your info

i have set it to a higher value coz i dont like ppl driving in "S" shape. after setting to a lower value (1.0.18f1) it resumed normal. thank you

btw, any chance to have "always green light going foward"? coz i have encountered some problems like below:

eg1 the traffic light marked in green should be disabled or allow green light always since it has no reason to show a red light in this case
![05-February-03-01-33-01](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/83495134/5842b334-23ae-4766-bc72-35503012df8f)


eg2 and this one, at the other side of T junction, going forward should be allowed without traffic light control
![05-February-03-00-16-00](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/83495134/a32105f3-ed10-4460-90d6-59d7baa28e7e)


eg3 this is embrassing... there were 4 lanes with 3 going forward and 1 right turn (in red). but since only left turn traffic allows always green lights, i had to make it like this, changed all going forward lanes as left turn on the left hand side
![05-February-14-38-11-00](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/83495134/aa4b384c-d3a2-4a9f-9b27-dd287e6c6831)


regards

**Comment by slyh** [comment]
I'm aware that the preset system has many limitations. Eventually, we will have pattern/phase customisation.

**Comment by xxjoe2** [comment]
yeah i understand 

thanks for your efforts anyway
