### ISSUE TITLE
Error on load after latest update

### ISSUE THREAD

**Issue by E2clipse** [slyh/Cities2-TrafficLightsEnhancement#79]
**Describe the bug**
An error message pops up after opening a saved game, after latest update
Only when game is not on pause , but unable to pan the camera. 
I do not know if this mod is the issue, I only received an error from this mod only.
As soon as you un pause, the game throws the error

**To Reproduce**
Update this mod and start a saved game

**Expected behaviour**
No error
[LogOutput.log](https://github.com/slyh/Cities2-TrafficLightsEnhancement/files/14119192/LogOutput.log)

**Screenshots**
![image](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/158389466/e9991697-114e-4ff5-8fe5-937c986d2449)

**Log file**
The error thrown in the log file

[Error  : Unity Log] [SceneFlow] [CRITICAL]  System update error during GameSimulation System.MissingMethodException: Method not found: Unity.Collections.NativeQueue`1<Game.Pathfind.SetupQueueItem> Game.Simulation.PathfindSetupSystem.GetQueue(object,int)
  at Unity.Entities.SystemBase.Update () [0x0004e] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Cities2Mods.CityPlayerTrafficCustomMods.CityPlayerCustomModsPatches.OnUpdate (Game.Simulation.HouseholdFindPropertySystem __instance) [0x0000b] in <39edbd5d832a44b48bb7f1544ad31ab8>:0 
  at (wrapper dynamic-method) Game.Simulation.HouseholdFindPropertySystem.DMD<Game.Simulation.HouseholdFindPropertySystem::OnUpdate>(Game.Simulation.HouseholdFindPropertySystem)
  at Unity.Entities.SystemBase.Update () [0x0004e] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Game.UpdateSystem.Update (Game.SystemUpdatePhase phase, System.UInt32 updateIndex, System.Int32 iterationIndex) [0x0007a] in <8bc3bf147d90443fb3df643f5b67c57a>:0

**Comment by sqorpo** [comment]
I have the same error

**Comment by Edou24** [comment]
me too

**Comment by slyh** [comment]
The occurrence of this error is likely due to the CityPlayerTrafficCustomMod has not been updated for 1.0.19f1 yet.

**Comment by E2clipse** [comment]
> The occurrence of this error is likely due to the CityPlayerTrafficCustomMod has not been updated for 1.0.19f1 yet.

Thanks for the quick reply!

**Comment by HarryBotter2333** [comment]
Yes, no error was reported after I closed it.

**Comment by E2clipse** [comment]
> The occurrence of this error is likely due to the CityPlayerTrafficCustomMod has not been updated for 1.0.19f1 yet.

Is there any timeframe of when the mod will be updated?

**Comment by HarryBotter2333** [comment]
> > 出现此错误的原因很可能是由于 CityPlayerTrafficCustomMod 尚未更新为 1.0.19f1。
> 
> mod有更新时间吗？

Keep wait, this update was already two weeks ago.

**Comment by slyh** [comment]
![PNG image](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/80482978/3d08b2a6-3020-4ad1-aed2-5232123c7fb4)

From CityPlayer's Discord server: https://discord.gg/RyBRtyuMQw

**Comment by Edou24** [comment]
i think that's great news

**Comment by E2clipse** [comment]
Is there any news? Can we at least have it so we can erase this from our builds, because I cannot afford to stop my build every update that comes out.

**Comment by E2clipse** [comment]
Ok so the workaround is, make a list of all installed mods except this one. De-install all of them, including this mod. Verify your game files. Start your game, exit. Install all mods except this and you can load your saves again.

**Comment by HarryBotter2333** [comment]
> 有消息了吗？我们至少可以拥有它，这样我们就可以从我们的构建中删除它，因为我不能在每次更新时停止我的构建。

I heard it will be updated in the next few weeks? I found on Cityplayer's Discord that the current beta version is V0.3.2 (latest?) and I only found V0.3.1. 

Then I loaded the TrafficCustomMod module and no error was reported. If you are interested you can try it. 

**Remember to back up your archive.**
