### ISSUE TITLE
Information about the update

### ISSUE THREAD

**Issue by slyh** [slyh/Cities2-TrafficLightsEnhancement#87]
Hello everyone,

I would like to update you on when this mod will be updated and its potential publication on PDX Mods.

Unfortunately, I am currently abroad in a timezone ahead of Europe. The beach properties update will be released at midnight my time, preventing me from working on it immediately. However, I aim to provide an update on Thunderstore as soon as possible.

I plan to migrate the mod to the official platform once I have access to the modding toolchain, which will be available to me at the same time as it is to everyone else. Still, no real progress should be expected until I return home in the first week of April.

I recognise this may inconvenience players who have put their trust in me by installing the mod. I sincerely apologise and will endeavour to address the situation promptly.

Thank you for your understanding.

**Update 30/3:** I have pushed [an update](https://github.com/slyh/Cities2-TrafficLightsEnhancement/releases/tag/0.2.19) targeting version 1.1.0f1. It's not yet available on Thunderstore. I would like to gather feedback before distributing it to more users.

**Update 16/4:** The mod is currently available for testing on [PDX Mods](https://mods.paradoxplaza.com/mods/78749/Windows). Please note that it is still in the testing phase, so ensure you have backups for your saves.

**Comment by HarryBotter2333** [comment]
No need worry, we wait you back : )

**Comment by brewcrew87** [comment]
For anyone checking this for the status of the mod update to PDX - know that this mod still works on the new update thru Thunderstore or installed manually.  I have been using this with all of my PDX mods with no issue.  

Sometimes when I launch the game from Thunderstore the PDX Mods don't seem to enable, but then I just browse the mods thru PDX Mods, then exit and reopen the game and for some reason that seems to work.  You can tell if the PDX mods are enabled before you enter a game by whether or not the warning for Achievements being disabled due to mods appears in the Load Game screen.

Hope that helps at least one person out there!  You don't have to wait!

**Comment by sealion200** [comment]
Good news is Traffic Lights Improvement still working in new version,thanks you for making mod!

**Comment by Tandent-zz** [comment]
> 好消息是交通信号灯改进仍在新版本中工作，感谢您制作模组！

Hello, how to use Cities2-TrafficLights in the new version?

**Comment by sealion200** [comment]
> > 好消息是交通號誌改進了新版本中的工作，感謝您製作模組！
> 
> 您好，請問新版的Cities2-TrafficLights如何使用？

you mean how to download or how to play?

**Comment by rons2112** [comment]
Just want to add my comment.  This is the mod that makes the game so much more playable for me, I love having more control over the traffic lights and lanes.  Can't wait until the PDX version, but for now, running it still via thunderstore still works.

**Comment by Tandent-zz** [comment]
> > > 好消息是交通號誌改進了新版本中的工作，感謝您製作模組！
> > 
> > 
> > 您好，請問新版的Cities2-TrafficLights如何使用？
> 
> you mean how to download or how to play?

I can't use it in the new version and don't know how to make it work.

**Comment by sealion200** [comment]
I use this ( https://paradoxmods.net/files/25-traffic-lights-improvement/ )，it need to Install [BepInEx 5]or [BepInEx 6] first , there have teaching.

**Comment by sealion200** [comment]
> > > > 好消息是交通號誌改進了新版本中的工作，感謝您製作模組！
> > > 
> > > 
> > > 您好，請問新版的Cities2-TrafficLights如何使用？
> > 
> > 
> > you mean how to download or how to play?
> 
> I can't use it in the new version and don't know how to make it work.

I use this ( https://paradoxmods.net/files/25-traffic-lights-improvement/ )，it need to Install [BepInEx 5]or [BepInEx 6] first , there have teaching.

**Comment by Tandent-zz** [comment]
> BepInEx
When installing the BepInEx framework in version 1.1.0F1, an error will be reported and the game cannot be entered.

**Comment by sealion200** [comment]
> > BepInEx
> > When installing the BepInEx framework in version 1.1.0F1, an error will be reported and the game cannot be entered.

Sorry I don`t know what worng. My mod still woking

**Comment by slyh** [comment]
> > BepInEx
> > When installing the BepInEx framework in version 1.1.0F1, an error will be reported and the game cannot be entered.

Could you share the error message?

**Comment by Ben0884** [comment]
Great to read that. Your mod is one of my absolut favorites and I'm really missing it @pdx mods.
But don't hassle, take the time you need. You already did an absolut fantastic job with this mod. Cheers

**Comment by evanre** [comment]
@slyh Thank you for the mod; it looks fantastic. I play CSII on the GeForce Now cloud service, which limits me to using only the built-in mods from Paradox. Do you have any updates on when it will be available on the Paradox platform?

**Comment by Idcaboutusernamer** [comment]
Welp, my BepInEx won't even start anymore, therefore this mod unfortunately isn't loaded.

**Comment by luckyfromCS2** [comment]
waiting on this mod specifically to be uploaded to the paradox mods to start a new city D:

**Comment by OutsideOctaves** [comment]
2 Weeks in to April, and coming back to check on the progress :D.  Hope it will drop on PDX soon :D

**Comment by pjdubya** [comment]
Hi @slyh . I have experience developing in C# and some free time so if you need a hand with anything on the update and would like a hand, just lmk. Thanks!

**Comment by Tandent-zz** [comment]
> > > BepInEx
> > > When installing the BepInEx framework in version 1.1.0F1, an error will be reported and the game cannot be entered.
> 
> Could you share the error message?

I'm sorry, dear developer, I haven't logged in to github for a while, and now I saw your message to me, and now it's resolved, and after I completely uninstalled and reinstalled my game, it works again.

**Comment by slyh** [comment]
**Update 16/4:** The mod is currently available for testing on [PDX Mods](https://mods.paradoxplaza.com/mods/78749/Windows). Please note that it is still in the testing phase, so ensure you have backups for your saves.

**Comment by slyh** [comment]
> Thank you for the mod; it looks fantastic. I play CSII on the GeForce Now cloud service, which limits me to using only the built-in mods from Paradox. Do you have any updates on when it will be available on the Paradox platform?

Unfortunately, I don't think Nvidia will allow arbitrary code mods running on their server, as people will use it to mine crypto.

> I have experience developing in C# and some free time so if you need a hand with anything on the update and would like a hand, just lmk. Thanks!

@pjdubya First of all, thank you for your kind offer. However, we need to address the licensing issue (most of the code is decompiled from the game) before I can accept contributions.

Let's put that aside for now. The most pressing issue is that the Lane Direction Tool is currently bundled with TLE, and I hope to spin it off into a separate mod. However, I must say the way LDT works is bodged at best, and I would feel very sorry for anyone to work on the current codebase. Also, it is likely that someone is working on a replacement for the LDT. So my advice is to stay put for the moment.

**Comment by pjdubya** [comment]
This is fantastic news! Congrats on getting this published. 

Sounds great on holding on helping for now. Feel free to PM me whenever you do find you could use a hand. I'm used to looking at confusing code from others so don't worry about that aspect, for what it's worth. For now I'll just do some testing and let you know if I run into issues. For what it's worth, I installed the TLE iMod Test via PDX Mods today and it seems to be working so far, although I did find at first that the TLE UI wouldn't appear when I was running it with other mods, all of which came from PDX Mods. I'm trying to isolate which one(s) caused the conflict for now and will post an issue once I do (although I know it's probably hard to determine whether TLE vs the conflicting mod need to make any change like this).

Thanks again for all that you do! Super excited to get to resuming playing CSII after waiting for this stuff to get sorted.

**Comment by slyh** [comment]
> although I did find at first that the TLE UI wouldn't appear when I was running it with other mods

Maybe it's just that sometimes the game doesn't load mods. I don't expect UI compatibility issues unless a mod is replacing menu icons.
