### ISSUE TITLE
MOD displays error when setting up

### ISSUE THREAD

**Issue by Tandent-zz** [slyh/Cities2-TrafficLightsEnhancement#92]
Dear developer, when I set up the TLE IMod Test, the road lane markings disappeared, as shown in the picture below. I don’t know if it is an incompatibility issue with the UI settings.
![屏幕截图(2)](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/16612843/4a1eb6cf-f21d-44d7-9e74-d5a7dfa87b99)

**Comment by Tandent-zz** [comment]
![屏幕截图(2)](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/16612843/4a1eb6cf-f21d-44d7-9e74-d5a7dfa87b99)

**Comment by slyh** [comment]
Is there any chance that you still have the BepInEx version installed?

**Comment by Tandent-zz** [comment]
> BepInEx

I'm using BepInEx, is it because I haven't deleted BepInEx, I'll try again later.

**Comment by Tandent-zz** [comment]
> Is there any chance that you still have the BepInEx version installed?

Dear developer, I still have this problem after deleting BepInEx, or even uninstalling the entire game and reinstalling it.

**Comment by slyh** [comment]
May I have your log files?

I need your ```Player.log``` and all the files inside the ```Logs``` folder located at ```%UserProfile%\AppData\LocalLow\Colossal Order\Cities Skylines II\```.

**Comment by slyh** [comment]
Could you try the latest update? It might have fixed this issue.

**Comment by Tandent-zz** [comment]
> Could you try the latest update? It might have fixed this issue.

Dear developers, the problem has indeed disappeared after I updated the mod version, thank you very much for your hard work.
