### ISSUE TITLE
Protected Left-Turns does not give green light to one direction

### ISSUE THREAD

**Issue by gaborposz** [slyh/Cities2-TrafficLightsEnhancement#97]
**Describe the bug**

Protected Left-Turns does not give green light to one direction.

![image](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/47426565/2824461b-63e0-4f13-9957-417369d59dad)

**To Reproduce**

1. Have an intersection
2. Set it to Protected Left-Turns
3. Wait

**Expected behaviour**

All directions gets their green lights.

**Log file**

[Logs.zip](https://github.com/slyh/Cities2-TrafficLightsEnhancement/files/15204815/Logs.zip)

**Additional context**
- Mod version: 0.1.21
- Other modes like Split Phasing are working well.
- It has happened right after the migration to the new Traffic mod, and I also modified the lane connections in this intersection, but I'm not sure if it has anything to do with it. Another intersection that I haven't touched is still working fine with the Protected Left-Turns mode.

**Comment by gaborposz** [comment]
It seems the Reset to Vanilla option in the Traffic mod fixed the issue... O_o
![image](https://github.com/slyh/Cities2-TrafficLightsEnhancement/assets/47426565/a72a15b2-d3c0-4aff-a27b-8a6c6747498b)

**Comment by slyh** [comment]
It seems protected turns are not compatible with removing uturns or unsafe. Migrated junctions have all unsafe lanes removed.

**Comment by slyh** [comment]
This issue should be fixed in version 0.2.22.

**Comment by gaborposz** [comment]
It works, thanks for the quick fix!
